"""Fit normalized spectral envelopes, not a measured transfer identification.

NumPy-only minimum-phase FIR design from real cepstra. The fitting objective is
the reference median spectral shape and pooled ear noise spectral shape, never
the achieved cancellation. No recorded phase/coherence is claimed to be preserved.
"""
import json
from pathlib import Path
import numpy as np

HERE = Path(__file__).parent
ROOT = HERE.parents[3]
NFFT = 16384
F = np.fft.rfftfreq(NFFT, 1 / 2000)


def response(path):
    return sum(g * np.exp(-2j * np.pi * F * d / 2000) for d, g in zip(path['delays'], path['gains']))


def smooth(power):
    grid = np.arange(-12, 13)
    kernel = np.exp(-.5 * (grid / 4) ** 2)
    kernel /= kernel.sum()
    # Four-Hz log-power smoothing retains broad resonances without pretending
    # a 40-second realization defines reproducible fine spectral lines.
    return np.exp(np.convolve(np.pad(np.log(np.maximum(power, 1e-30)), 12, mode='edge'), kernel, 'valid'))


def minimum_phase(power, length):
    cepstrum = np.fft.irfft(.5 * np.log(np.maximum(power, power.max() * 1e-10)), n=NFFT)
    causal = np.zeros(NFFT)
    causal[0] = cepstrum[0]
    causal[1:NFFT//2] = 2 * cepstrum[1:NFFT//2]
    causal[NFFT//2] = cepstrum[NFFT//2]
    full = np.fft.irfft(np.exp(np.fft.rfft(causal)), n=NFFT)
    h = full[:length].copy()
    h[-32:] *= .5 * (1 + np.cos(np.linspace(0, np.pi, 32)))
    return h


def shape(h):
    return np.abs(np.fft.rfft(h, n=NFFT)) ** 2


def normalize(p):
    return p / np.trapezoid(p, F)


def fit():
    audit = json.loads((HERE / 'audit.json').read_text('utf-8'))
    data = np.load(HERE / 'spectral-audit.npz')
    freq, psd = data['frequency_hz'], data['psd_raw_units']
    active = [c['channel'] - 1 for c in audit['channels'][:48] if c['rms_ac'] > 0 and c['unique'] > 1]
    band = (freq >= 1) & (freq <= 1000)
    reference = np.median(psd[:, active] / psd[band][:, active].sum(axis=0), axis=1)
    noise = psd[:, 48:].mean(axis=1)
    ref_target = normalize(np.interp(F, freq, smooth(reference)))
    noise_target = normalize(np.interp(F, freq, smooth(noise)))
    # Mean removal was confined to PSD estimation; keep the sub-50 Hz band.
    # Taper the last 100Hz to zero for the 2kHz simulator's Nyquist boundary.
    taper = np.ones(len(F))
    taper[F > 900] = np.cos((F[F > 900]-900)/100*np.pi/2) ** 2
    ref_target *= taper
    noise_target *= taper
    geometry = json.loads((HERE / 'teaching-geometry.json').read_text('utf-8'))
    r = np.mean([sum(np.abs(response(path))**2 for path in row) for row in geometry['reference']], axis=0)
    h = np.mean([sum(np.abs(response(path))**2 for path in row) for row in geometry['primary']], axis=0)
    source = minimum_phase(ref_target / np.maximum(r, r.max()*1e-4), 255)
    source /= np.sqrt(np.sum(source**2)/3)  # unit RMS for uniform[-1,1] excitation
    q = shape(source)
    ratio = noise_target / np.maximum(normalize(q*h), 1e-12)
    color = minimum_phase(ratio, 129)
    # Keep the former teaching gain scale independent of uncalibrated volts.
    color *= np.sqrt(np.sum(q*h) / np.sum(q*h*shape(color)))
    new_ref, new_noise = normalize(q*r), normalize(q*h*shape(color))
    # Old generator's two deterministic sinusoidal lines plus 97-tap bandpass.
    t = np.arange(97)-48
    old_source = (.36*np.sinc(.36*t)-.035*np.sinc(.035*t)) * np.hamming(97)
    old_source /= np.sqrt(np.sum(old_source**2)/3)
    old_q = .88**2*shape(old_source)/3
    for hz, amplitude in [(95, .24), (220, .18)]:
        old_q[np.argmin(abs(F-hz))] += amplitude**2/2/(F[1]-F[0])*1000
    old_ref, old_noise = normalize(old_q*r), normalize(old_q*h)
    profile = dict(id='bev-40-rough-voltage-spectrum-v1', sampleRateHz=2000,
                   measuredSampleRateHz=4000, measuredDurationSeconds=40,
                   baselineSpeedKph=40, originalUnit='V', calibrated=False,
                   includedReferenceChannels=[i+1 for i in active], primaryChannels=list(range(49,57)),
                   sourceSha256=audit['source_sha256']['pri.dat'],
                   sourceFir=source.tolist(), primaryColorFir=color.tolist())
    target = ROOT / 'src/team-b/lab/recorded-profile.ts'
    target.write_text('// Generated by docs/evidence/B/B1-DATA-001/fit_profile.py.\n'
                      '// Normalized spectral envelope only; no MATLAB algorithms or measured calibration.\n'
                      'export const RECORDED_PROFILE = ' + json.dumps(profile, ensure_ascii=False, indent=2) + ' as const;\n', encoding='utf-8')
    bands = [(1,20),(20,50),(50,100),(100,200),(200,350),(350,600),(600,1000)]
    def fractions(p):
        return [float(np.sum(p[(F>=a)&(F<b)]) / np.sum(p[F>=1])) for a,b in bands]
    def error(p, target):
        return float(np.mean(np.abs(10*np.log10(np.maximum(fractions(p),1e-15)/np.maximum(fractions(target),1e-15)))))
    comparison = dict(bands_hz=bands,
                      reference=dict(recorded=fractions(ref_target), old=fractions(old_ref), fitted=fractions(new_ref)),
                      primary=dict(recorded=fractions(noise_target), old=fractions(old_noise), fitted=fractions(new_noise)),
                      mean_band_error_db=dict(reference_old=error(old_ref,ref_target), reference_fitted=error(new_ref,ref_target),
                                              primary_old=error(old_noise,noise_target), primary_fitted=error(new_noise,noise_target)),
                      interpretation='Envelope match at default BEV geometry, 240kPa/20C. Normalized power only, not real SPL or cancellation.')
    (HERE/'fit-comparison.json').write_text(json.dumps(comparison,indent=2),encoding='utf-8')
    np.savez_compressed(HERE/'fitted-envelope.npz', frequency_hz=F, reference_target=ref_target, primary_target=noise_target,
                        reference_old=old_ref, primary_old=old_noise, reference_fitted=new_ref, primary_fitted=new_noise)
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    fig, axs = plt.subplots(1,2,figsize=(12,4),constrained_layout=True)
    for ax, title, target, old, new in zip(axs,['Reference spectral envelope','Primary noise spectral envelope'],
                                           [ref_target,noise_target],[old_ref,old_noise],[new_ref,new_noise]):
        for p,label in [(target,'Recorded target (normalized)'),(old,'Previous teaching model'),(new,'Fitted teaching model')]:
            ax.plot(F,10*np.log10(np.maximum(p,1e-15)),label=label)
        ax.set(xlim=(1,600),ylim=(-85,-5),xlabel='Frequency / Hz',ylabel='Normalized PSD / dB/Hz',title=title)
        ax.grid(alpha=.25); ax.legend(fontsize=8)
    fig.savefig(HERE/'envelope-comparison.png',dpi=170)
    actual_file = HERE / 'simulated-x-d.f32'
    if actual_file.exists():
        samples = np.fromfile(actual_file, dtype='<f4').reshape(-1, 8)
        window = .5 - .5*np.cos(2*np.pi*np.arange(2000)/2000)
        # Skip first second of synthesis startup; no generated data is altered.
        measured = np.mean([abs(np.fft.rfft((samples[n:n+2000]-samples[n:n+2000].mean(axis=0))*window[:,None],axis=0))**2
                            for n in range(2000,len(samples)-1999,1000)],axis=0)
        actual_ref = normalize(np.interp(F,np.arange(1001),measured[:,:4].mean(axis=1)))
        actual_noise = normalize(np.interp(F,np.arange(1001),measured[:,4:].mean(axis=1)))
        actual = dict(reference_bands=fractions(actual_ref),primary_bands=fractions(actual_noise),
                      mean_band_error_db=dict(reference=error(actual_ref,ref_target),primary=error(actual_noise,noise_target)),
                      source='actual 16s TypeScript batch, seed11, BEV40kph, 240kPa/20C; analysis skips startup first1s')
        (HERE/'actual-spectrum-check.json').write_text(json.dumps(actual,indent=2),encoding='utf-8')
        assert actual['mean_band_error_db']['reference'] < 1.5
        assert actual['mean_band_error_db']['primary'] < 1.5
        print('Actual signal comparison:', json.dumps(actual,indent=2))
    print('Analytical band errors:', comparison['mean_band_error_db'])


if __name__ == '__main__':
    fit()
