"""Standalone NumPy design of a causal teaching A-weighting FIR at 2kHz.
Not the user's MATLAB processing. Not a certified full-audio-band sound meter.
"""
import json
from pathlib import Path
import numpy as np

here = Path(__file__).parent
root = here.parents[3]
n = 16384
f = np.fft.rfftfreq(n, 1/2000)
def amplitude(frequency):
    f2 = np.asarray(frequency, dtype=float)**2
    return 12194.**2*f2**2 / ((f2+20.6**2)*np.sqrt((f2+107.7**2)*(f2+737.9**2))*(f2+12194.**2))
a = amplitude(f)/amplitude(1000.)
c = np.fft.irfft(np.log(np.maximum(a,1e-12)),n)
m = np.zeros(n); m[0]=c[0]; m[1:n//2]=2*c[1:n//2]; m[n//2]=c[n//2]
h = np.fft.irfft(np.exp(np.fft.rfft(m)),n)[:65]
h[-16:] *= .5*(1+np.cos(np.linspace(0,np.pi,16)))
h /= abs(np.sum(h*(-1.)**np.arange(len(h))))
freq = np.array([20,31.5,50,63,100,125,250,500,800,1000.])
actual = abs(np.exp(-2j*np.pi*freq[:,None]*np.arange(len(h))/2000)@h)
errors = 20*np.log10(actual/(amplitude(freq)/amplitude(1000.)))
assert max(abs(errors)) < .2
(root/'src/team-b/lab/a-weighting-fir.ts').write_text('// Generated by B1-ANALYSIS-001/design_weighting.py; 2kHz, 65 taps.\n'
    'export const A_WEIGHTING_FIR = '+json.dumps(h.tolist(),indent=2)+' as const;\n',encoding='utf8')
(here/'a-weighting-design.json').write_text(json.dumps(dict(frequency_hz=freq.tolist(),error_db=errors.tolist(),
    sample_rate_hz=2000,taps=len(h),certified_sound_meter=False),indent=2),encoding='utf8')
print('A-weighting response error / dB:',errors)
